# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockershrink < Formula
  desc "A commandline tool to reduce the size of Nodejs Docker images"
  homepage "https://dockershrink.com/"
  version "0.1.0"

  depends_on "go"

  on_macos do
    on_intel do
      url "https://github.com/duaraghav8/dockershrink-cli/releases/download/v0.1.0/dockershrink_0.1.0_darwin_amd64.tar.gz"
      sha256 "23758508c5d532104c60df89d0564f38bd33b5021241b7cd52ebf21a225f88e0"

      def install
        bin.install "dockershrink"
      end
    end
    on_arm do
      url "https://github.com/duaraghav8/dockershrink-cli/releases/download/v0.1.0/dockershrink_0.1.0_darwin_arm64.tar.gz"
      sha256 "176282702f57c4f108f040a1b118752707efb7d0ef6f80a24c4b846ce0697419"

      def install
        bin.install "dockershrink"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/duaraghav8/dockershrink-cli/releases/download/v0.1.0/dockershrink_0.1.0_linux_amd64.tar.gz"
        sha256 "a3edc985adce455c497fd020c866a4bc53bd90fe58622b36f3d1deb32677d4eb"

        def install
          bin.install "dockershrink"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/duaraghav8/dockershrink-cli/releases/download/v0.1.0/dockershrink_0.1.0_linux_arm64.tar.gz"
        sha256 "fc5e0c3892ef34aba9553a20b29aeb48eeb24eeeaaabc5de89ef357905b3c850"

        def install
          bin.install "dockershrink"
        end
      end
    end
  end
end
