# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockershrink < Formula
  desc "AI tool to reduce the size of Docker images"
  homepage "https://github.com/duaraghav8/dockershrink"
  version "0.1.7"

  depends_on "go"

  on_macos do
    on_intel do
      url "https://github.com/duaraghav8/dockershrink/releases/download/v0.1.7/dockershrink_0.1.7_darwin_amd64.tar.gz"
      sha256 "d845fe30b989e5c3312a1675b82b33bc9e62a186458df8827f9b7f1a5f67527f"

      def install
        bin.install "dockershrink"
      end
    end
    on_arm do
      url "https://github.com/duaraghav8/dockershrink/releases/download/v0.1.7/dockershrink_0.1.7_darwin_arm64.tar.gz"
      sha256 "0a44b9f32040e6ec95aef1a52ce80123bac0394a84a0dbea08619077e1633eae"

      def install
        bin.install "dockershrink"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/duaraghav8/dockershrink/releases/download/v0.1.7/dockershrink_0.1.7_linux_amd64.tar.gz"
        sha256 "47cf8e81d79ef963f8dbdfff3419655c6e870b8691f38e3ac4ce1b8a9858ac67"

        def install
          bin.install "dockershrink"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/duaraghav8/dockershrink/releases/download/v0.1.7/dockershrink_0.1.7_linux_arm64.tar.gz"
        sha256 "53ce2d4c13433dd4b22adf7cfe79817955d7912a21f47bdc79840b140011e244"

        def install
          bin.install "dockershrink"
        end
      end
    end
  end
end
